### ISSUE TITLE
P_EPX_0740_0* cannot be decrypted

### ISSUE THREAD

**Issue by marquezclaudio** [3MFConsortium/test_suites#80]
The P_EPX_0740_0*.3mf files seem to be malformed (suite5_core_prod/positive_test_cases_prod_alt/prod_alt_secure_content_tests/).

For instance, for the file P_EPX_0740_01.3mf, we have detected an issue with the Keystore attribute "consumerindex" value due to it mismatches the testing public key, as can be seen in the file keystore.xml. However, if we fix the provided attribute "consumerindex", the "cipherdata" and "cekparams" seem to be incorrect as well. It was impossible for us to decrypt these files.

Also, the 3mfEditor reports problems with the decryption of such files.
![image](https://github.com/3MFConsortium/test_suites/assets/4638616/8b9e09e3-3ca2-4b3e-85c2-60d38d5a14c2)

Could you please verify this issue?

**Comment by JimZuber** [comment]
These test cases contain models that are encrypted, but the render does not have the permissions to decrypt. If you refer to the Alternative Combination Table on page 31 of the 3MF test specification, the items Sec_01 to Sec_06 map to test cases 0740_01 through 0740_06.  In the table "E" means that the model is encrypted but the renderer does not have the key to decrypt. If the table has "E_A" that means that the model encrypted and the renderer does have access to the key needed to decrypt. 

So, in each test case there will be at least one model that the renderer cannot access because it does not have permission (i.e. a key) to access the file. In this case, the renderer should find another alternative. The 3MF editor is also going to report a decryption error as it also does not have the key for some models. This is as expected. For instance in test 0740_01, which uses Sec_01 from the table, the primary image model is encrypted but the renderer does not have access. This is exactly what the listing in you provided shows. However, the Alt_1 model is encrypted and the renderer has access, and you can see from the 3MF editor validation listing, it report no problems decrypting this model. 

I noticed that the 3MF editor was not continuing with the structure check because of the files it found that could not be decrypted. You can modify the following 3MF Editor Property to enable structure checks in this situation (make sure to reload the properties after editing from the Tools menu). 

# If true, do structure checks even if there are schema validation errors
   bStructureChkWerrors = "true"

I beleive that the test cases are correct. The 3MF implementation under test should select an alternative if it does not have permission to decrypt a give model file. Note that the models in the 3MF packages that were encrypted where the renderer does not have permission are NOT going going to be able to be decrypted by shuffling around references in the keystore. The needed information in to decrypt is NOT available to the renderer.

Hope all this makes sense!

**Comment by jordig100** [comment]
Hi Jim.

I think you are right. It should take the alternative model 1 instead of the primary object model. In fact due to the alternatives order, even if the primary object model where available, it should also take the alt1.

What I miss in the test cases is that both the primary are available and fullres, and in this case it should take alt1. In all test cases never has this conflict so it decides by the alternative order.

On the 3mfEditor, I enabled the bStructureChkWerrors = "true", and now I get:


XML validation for "3dmodel.model" did not return any errors.  
Decrypted \3D\alt1.model XML validation for "alt1.model" did not return any errors.  
XML validation for "alt2.model" did not return any errors.  
Decryption failure for \3D\primary.model 
**XML validation aborted for file \3D\primary.model  
XML validation for "3dmodel.model.rels" did not return any errors.**  
XML validation for "keystore.xml" did not return any errors.  
XML validation for "[Content_Types].xml" did not return any errors.  
XML validation for ".rels" did not return any errors.  
**ER_057: Did not find an object id for item with objectid=7 in /3D/3dmodel.model  
ER_059: /3D/primary.model was found but did not start with ?xml.**   
**Structural check failure on D:/jordig/OneDrive - HP Inc/TestFiles/3MF/Alternatives/prod_alt_secure_content_tests/P_EPX_0740_01.3mf which appears to be using encryption.** 

The complaining objectID 7, is alt1, which can be decrypted. And I see the objectID exists in the decrypted model.

**Comment by jordig100** [comment]
Closing the original issue, and splitting the other two issues in independent issues.
