### ISSUE TITLE
Missing an alternative test case with two fullres available

### ISSUE THREAD

**Issue by jordig100** [3MFConsortium/test_suites#82]
No test case that covers when two or more models are available for the consumer and has to chose which one to select based only on the alternatives order.

Specially when the primary object is available, and has a second alternative, it has to chose the alternative first. In current test cases there is at most 1 model available for the consumer with fullres, so it doesn't test the alternative order.

**Comment by JimZuber** [comment]
I think that test case P_XPX_0720 does test this. The primary model is full res and the alternate model doesn't have a specified resolution, which by default is full res. The expected result is that it selects Alt 1. We could do something more explicit (Specify a resolution of full res rather than undefined resolution), but I think this test case does cover the use case you describe.

**Comment by jordig100** [comment]
Test case P_XPX_0720.07 then cover this test case by specifying the primary as fullres and the alt1 undefined, with defaults to fullres. The alternatives order makes to select the alt1 model.

Thanks Jim for pointing it out.
